### ISSUE TITLE
Use of PrometheusRule for "Certificate soon to expire event" to create OpenShift Altert would be great

### ISSUE THREAD

**Issue by aletsche** [redhat-cop/cert-utils-operator#101]
Thanks for this operator. Did not yet check all features but those I tried since yesterday work as documented! :)

I especially like the feature to be informed if a certificiate is soon to expire.

However, on a large platform with a lot of projects/namespaces it is not really practical to manually look into the project to see the "soon to expire events". It is possible to create a job which sends an email to alert somebody based on "oc get events" of course. However, it would be perfect if a metric would be available that can be used for a PrometheusRule and send the Alter via the OpenShift Cluster Monitoring (Alertmanager). 

I searched vi Google to find a way to get an Alert for a Kubernetes Event but didn't find a solution yet.
It seems that we have to go the Job-way. Anyway, better than implementing a solution on our own.

**Comment by ocpvkb** [comment]
Request +1 :-)
