### ISSUE TITLE
Operator broke on OKD and Kubernetes

### ISSUE THREAD

**Issue by aelbarkani** [redhat-cop/cert-utils-operator#102]
There was a change in the image which breaks the operator for non Redhat users:
https://github.com/redhat-cop/cert-utils-operator/blob/b238fd4a0cb5453168f36aaa9f5fc91b96c1dc2f/config/default/manager_auth_proxy_patch.yaml#L13

**Comment by nevidanniu** [comment]
any news?

**Comment by garethahealy** [comment]
@nevidanniu see: https://github.com/redhat-cop/namespace-configuration-operator/issues/118
