### ISSUE TITLE
cert-utils-operator cannot list routes at cluster scope

### ISSUE THREAD

**Issue by Gl4di4torRr** [redhat-cop/cert-utils-operator#12]
Hi,

I have deployed the cert-operator. However, I am getting a constant error like this below.

```sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Route: routes.route.openshift.io is forbidden: User "system:serviceaccount:cert-manager:cert-utils-operator" cannot list routes.route.openshift.io at the cluster scope: User "system:serviceaccount:cert-manager:cert-utils-operator" cannot list all routes.route.openshift.io in the cluster```

Some outputs:
```
$ oc get sa cert-utils-operator
NAME                  SECRETS   AGE
cert-utils-operator   2         3h

$ oc get role
NAME
cert-utils-operator

$ oc get rolebinding cert-utils-operator
NAME                  ROLE                               USERS     GROUPS    SERVICE ACCOUNTS      SUBJECTS
cert-utils-operator   cert-manager/cert-utils-operator                       cert-utils-operator 
```

**Comment by raffaelespazzoli** [comment]
the manifests assume you are going to deploy the cert-utils-operator in the `cert-utils-operator` namespace.
please update the role-binding.yaml if you want to deploy it in a different namespace. 
I should fix this by creating a template to deploy the operator.

**Comment by Gl4di4torRr** [comment]
@raffaelespazzoli gotcha - i was thinking that might be the issue. What do you think about that picking up the target namespace or a doc on how to change the target namespace?

**Comment by raffaelespazzoli** [comment]
I'll create an issue to create a helm chart. or if you have a 4.x cluster you can install the operator via operator hub.
