### ISSUE TITLE
ConstraintsNotSatisfiable - V1.3.9

### ISSUE THREAD

**Issue by dylandeflavia** [redhat-cop/cert-utils-operator#131]
Hi, I tried to uninstall and re-install a new version of the cert-utils-operator however I get the below error:

`constraints not satisfiable: @existing/cert-utils-operator//cert-utils-operator.v1.3.9 and community-operators/openshift-marketplace/alpha/cert-utils-operator.v1.3.9 originate from package cert-utils-operator, subscription cert-utils-operator requires community-operators/openshift-marketplace/alpha/cert-utils-operator.v1.3.9, subscription cert-utils-operator exists, clusterserviceversion cert-utils-operator.v1.3.9 exists and is not referenced by a subscription`

`operator.v1.3.9 exists and is not referenced by a subscription, subscription cert-utils-operator requires at least one of community-operators/openshift-marketplace/alpha/cert-utils-operator.v1.3.9, community-operators/openshift-marketplace/alpha/cert-utils-operator.v1.3.8, community-operators/openshift-marketplace/alpha/cert-utils-operator.v1.3.7, community-`

I am guessing there might be residual files, but cannot find any. 

Thanks!

**Comment by raffaelespazzoli** [comment]
hello, I had similar issues with other operators. I don't know how to fix them it looks like an OLM problem. Can you try uninstall the operator and reinstalling it? It should not affect your current certificates.

**Comment by dylandeflavia** [comment]
Thank you Raffaele.

Tried to uninstall and re-install the operator but getting the constraint errors.

![image](https://user-images.githubusercontent.com/57752261/163401457-c9b2c0ac-51b5-4b03-93da-b7961e6ff366.png)

**Comment by dylandeflavia** [comment]
@raffaelespazzoli - Thank you for pointing me in the right direction 👍 

Basically, I managed to install the cert-utils-operator in the same namespace which is the recommended. 

Issue was with the catalog-operator: restarted the operator and worked.
