### ISSUE TITLE
Cannot inject destinationCA with cert-utils in reencrypt type of openshift routes

### ISSUE THREAD

**Issue by BrankoPavlovic10** [redhat-cop/cert-utils-operator#172]
Hi all,
I am using Openshift 4.14 and I have route, which i annotated like this
![image](https://github.com/user-attachments/assets/d4917e95-07ab-4271-97e9-d4daa49ab52d)

This first annotation means that I will inject tls.key and tls.crt from route-certificate-ca secret.
The second annotation will inject destinationCA from the same secret. (I also tried from inject it from separate secret, but that did not work)
Third annotation will just not inject caCertificate from the same secret. (I do not need that parameter).

And although i have that route that i need in same 'elastic' namespace
![image (1)](https://github.com/user-attachments/assets/62f2d94b-cc05-4ef9-afe3-7927385d5fb7)
I still cannot inject that destionationCA certificate in my route.
The destinationCA just wont appear when I deploy route.

Beside, everything works great with edge type of routes (Only difference with edge routes are that they do not require destionationCA)... 

I also checked logs of deployment of cert-utils operator, logs inside the pod and it's 2 container but there is nothing about this problem...

Hope that someone can help :)

**Comment by raffaelespazzoli** [comment]
what are the keys of the secret?

**Comment by BrankoPavlovic10** [comment]
Hi @raffaelespazzoli, 
We can see key in output of the following command

![image](https://github.com/user-attachments/assets/23fc1ee9-8f9a-4749-a86a-582c759a11a2)

**Comment by BrankoPavlovic10** [comment]
At the time, I used latest version of my operator and it was 1.3.12.

But the thing that fixed my problem was reinstalling operator to earlier (1.3.11) version.

Everything else remained the same, and after installation of 1.3.11 version, it started to work as expected.

**Comment by mathianasj** [comment]
@BrankoPavlovic10  Did the issue reoccur when you upgraded to 1.3.12?

**Comment by BrankoPavlovic10** [comment]
> @BrankoPavlovic10 Did the issue reoccur when you upgraded to 1.3.12?

Not sure, I left it on 1.3.11
