### ISSUE TITLE
Add v0.0.3 of operator to OpenShift and Upstream Community Operators

### ISSUE THREAD

**Issue by ron1** [redhat-cop/cert-utils-operator#28]
Since most of the functionality of this operator is useful to the upstream Kubernetes community, consider making v0.0.3 available to both the OpenShift and upstream communities on OperatorHub.io.

**Comment by raffaelespazzoli** [comment]
right now the operator requires routes, which are not available in Kubernetes. However it may be possible to add a flag to disable the route controller and use the rest of the functionalities in a Kubernetes  instance.

**Comment by ron1** [comment]
Would it be possible on startup to only enable the route controller if the route api resource is available?

**Comment by raffaelespazzoli** [comment]
I think it should be possible, and this is a good idea.
