### ISSUE TITLE
Invalid secret name causes crash

### ISSUE THREAD

**Issue by mathianasj** [redhat-cop/cert-utils-operator#48]
If you do not specify a secret with namespace/secret the controller will crash.

E0427 14:40:52.174434   56565 runtime.go:78] Observed a panic: runtime.boundsError{x:-1, y:8, signed:true, code:0x1} (runtime error: slice bounds out of range [:-1])

**Comment by mathianasj** [comment]
It would be better to attach a status to the annotated entry with an error message

**Comment by raffaelespazzoli** [comment]
this is a bit obscure. Which controller is failing? under which condition exactly?

**Comment by mathianasj** [comment]
I noticed with the config map controller for cainjector specifically.  If I do not follow namespace/secret-name is what causes a crash.  If I annotate with any of the following below.

Config Map Annotation
cert-utils-operator.redhat-cop.io/injectca-from-secret: secret-name

Secret Annotation
cert-utils-operator.redhat-cop.io/injectca-from-secret: secret-name

**Comment by mathianasj** [comment]
If that happens the pod goes into a crash loop

**Comment by raffaelespazzoli** [comment]
ok, the input is not correctly validated before being processed. The operator should simply fail without panicking.
