### ISSUE TITLE
Java Truststore from ConfigMap

### ISSUE THREAD

**Issue by mathianasj** [redhat-cop/cert-utils-operator#52]
I would like to be able to generate a java truststore from a configmap so I can utilize the "config.openshift.io/inject-trusted-cabundle" label.  This will enable me to consume the ca trusts that are configured at a cluster level for an environment and pass them on to Java applications and remove the need to create custom images for trust.

**Comment by raffaelespazzoli** [comment]
yes. in openshift now there seem to be a new standard by which ca are made available via configmap. We can certainly add that capability.
In the meantime you might try to use the resource-locker-operator[1] to inject the configmap field into a secret.

[1]: https://github.com/redhat-cop/resource-locker-operator

**Comment by mathianasj** [comment]
Will close and implement #55 instead

**Comment by mathianasj** [comment]
Reopening as this is working, I did not know that configmaps had a binarydata section now.
