### ISSUE TITLE
Broken in OpenShift 4.5

### ISSUE THREAD

**Issue by milosgajdos** [redhat-cop/cert-utils-operator#66]
We were using this wonderful operator to automatically inject TLS certs generated by cert- manager into routes, but after upgrade to 4.5 we started noticing the following errors in the logs:
```
E0729 15:30:02.323442       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.APIService: apiservices.apiregistration.k8s.io is forbidden: User "system:serviceaccount:cert-utils-operator:cert-utils-operator" cannot list resource "apiservices" in API group "apiregistration.k8s.io" at the cluster scope
E0729 15:30:23.831148       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1.APIService: apiservices.apiregistration.k8s.io is forbidden: User "system:serviceaccount:cert-utils-operator:cert-utils-operator" cannot list resource "apiservices" in API group "apiregistration.k8s.io" at the cluster scope
```

We install the operator using Helm chart, I think it's missing the following rules in the clusterrole:
```
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - '*'
```
Possibly with fine-tuned verbs.

**Comment by mathianasj** [comment]
Did you update your deployment chart to use the updates located here https://github.com/redhat-cop/cert-utils-operator/blob/1059e69aec371e3ff80b9cf30b6c0a4baaea8e0d/deploy/role.yaml#L35

I see that the updated requirements are included under the deploy folder.

**Comment by mathianasj** [comment]
I actually misspoke, it looks like we did not propagate the changes into the helm chart also for role.  Would you be interested in creating a pull request with the addition?

**Comment by milosgajdos** [comment]
The rules seem to be in the default branch already, where how do you folks maintain your Helm chart? I'm happy to open a PR indeed once I know where I can find it

**Comment by mathianasj** [comment]
Thank you for looking to contribute, the chart and specifically where the role file is in the chart is located here

https://github.com/redhat-cop/cert-utils-operator/blob/master/charts/cert-utils-operator/templates/role.yaml

**Comment by milosgajdos** [comment]
Oh :-) I must've gone blind. Thanks, will open a PR in a minute!
