### ISSUE TITLE
When are you planning to release the latest helm chart?

### ISSUE THREAD

**Issue by milosgajdos** [redhat-cop/cert-utils-operator#74]
We would love to have #67 in our cluster from the upstream rather than maintaining our fork.
Equally, we would appreciate if you could consider merging #71 in as well :-)

**Comment by mathianasj** [comment]
#67 should be available now, we reran the release of the helm chart after that was merged.  Can you try installing with the chart again?  I will take a look at #71 today.  Thanks again!

**Comment by milosgajdos** [comment]
Thanks, #67 seems to be in the latest release 👍
