### ISSUE TITLE
Opaque secrets

### ISSUE THREAD

**Issue by aceeric** [redhat-cop/cert-utils-operator#75]
It would be beneficial to have the cert-utils-operator to inject a JKS from an Opaque secret. Here's the use case:

1) Deploy Elastic Cloud for Kubernetes (ECK) Operator into the cluster
2) Create a CR `elasticsearch.k8s.elastic.co/v1/elasticsearch` named nxelastic
3) ECK Operator creates an ElasticSearch cluster and also creates **opaque** secret named `nxelastic-es-http-certs-public`
4) Create a secret `my-elasticsearch-binding` annotated to have cert-utils-operator inject the CA from `nxelastic-es-http-certs-public` into it
5) Mount secret `my-elasticsearch-binding` into a Deployment  that runs a Java app to allow that deployment to connect to ElasticSearch using TLS

It appears based on the README - "Certificates are assumed to be available in a secret of type kubernetes.io/tls (other types of secrets are ignored by this operator)" - and experimentation - that this use case is intentionally not supported. Do you see a benefit from implementing this capability?

**Comment by raffaelespazzoli** [comment]
no, I don't think we should support this use case.
just for me to understand what is the content of the `nxelastic-es-http-certs-public` secret? A truststore or PEM formatted certificates?
Anyway generally speaking Middleware should not create their own certificates. They are now a PKI, they can meet the requirements of a PKI. Middleware should be designed to accept certificates created with some other means and injected via secrets or configmaps (in the case of the CA).
@mathianasj do you want to weigh in on this?

**Comment by aceeric** [comment]
`nxelastic-es-http-certs-public` is provisioned by the Elastic Cloud operator. It contains `ca.crt` and `tls.crt`. ECK is available on OperatorHub.io. Whether the "middleware" creates the secret or not is not really knowable to the consumer. The operator is basically saying "this is the CA you use if you want to use one-way TLS to connect to my service." The CA could have been provisioned by any cluster entity. Please have a look at https://operatorhub.io/operator/elastic-cloud-eck

**Comment by raffaelespazzoli** [comment]
@aceeric OK thanks. so it's in PEM format. I still argue that that operator should give you an option to pass it the certs to use instead of generating them. 
A possible workaround to use this operator[1] to inject the PEM-formatted certs to a secret of type TLS, from there you can use the cert-utils operator. Look for the patching feature. 

[1]: https://github.com/redhat-cop/resource-locker-operator
