### ISSUE TITLE
Latest version of cert-utils-operator does not support OpenShift 3.11

### ISSUE THREAD

**Issue by aceeric** [redhat-cop/cert-utils-operator#76]
With the change from 0.1.0 to 0.1.1, the cert-utils-operator does not support OpenShift 3.11. The operator uses `k8s.io/appextensions-apiserver/pkg/apis/apiextensions/v1`. But:
```
$ oc version
oc v3.11.188
kubernetes v1.11.0
openshift v3.11.146
```
And
```
$ oc api-versions | grep apie
apiextensions.k8s.io/v1beta1
```
Do you see value in supporting the `v1` CRD as well as the `v1beta1` CRD for OpenShift 3.11 compatibility. If not, users can only use cert-utils-operator v0.1.0 until they upgrade their OpenShift cluster.

**Comment by raffaelespazzoli** [comment]
@mathianasj I thought we disabled the controller that needed to watch for CRDs to support running on OCP 3.x.
Can you confirm if we still have this issue?

**Comment by dejwsz** [comment]
This problem lasts from version v0.1.1 in Openshift 3.11. Any solution to this?
I have a problem with old version v0.1.0 because it removes 'ca.crt' keys from 'kubernetes.io/tls'. secrets. I wanted to upgrade to see if the problem is solved.

**Comment by mathianasj** [comment]
Cert-utils-operator is currently only supporting OpenShift 4.x and newer.  We welcome pull requests and I would be happy to review one to address the issues with 3.11.
