### ISSUE TITLE
Base image need to be updated or Rebuild from latest need to be updated on Quay.

### ISSUE THREAD

**Issue by amelie1979** [redhat-cop/cert-utils-operator#77]
source: quay.io/redhat-cop/cert-utils-operator:latest
Quay Security Scanner has detected 52 vulnerabilities.
Patches are available for 52 vulnerabilities.
 8 High vulnerabilities.
 33 Medium vulnerabilities.
 11 Low vulnerabilities.

Its also affecting OCP operator provide in OCP 4.5.11
Container security is flagging the image.

That would be interesting to receive an email or webhook from Quay when scanner detect CVE.

**Comment by mathianasj** [comment]
Going to take a look at this and looks like it should be an easy fix
