### ISSUE TITLE
Conflict when installing cert-utils-operator with other redhat-cop operators ?

### ISSUE THREAD

**Issue by aelbarkani** [redhat-cop/cert-utils-operator#88]
I've noticed that having this operator installed with other redhat-cop operators like https://github.com/redhat-cop/resource-locker-operator in the same cluster is causing problems to OLM. The other operators seems to be stuck in Pending state.
Maybe because the SA used is default ? I've noticed that this issue doesn't happen with https://github.com/redhat-cop/namespace-configuration-operator since some days ago the have changed the SA name.

**Comment by raffaelespazzoli** [comment]
this should be fixed by #87
